### ISSUE TITLE
The profanity filter removed "?@@^%$" from my comment, but it wasn't used in a profane way.

### ISSUE THREAD

**Issue by mdell-seradex** [IEvangelist/profanity-filter#31]
In https://github.com/dotnet/docs/pull/40794#issuecomment-2138172984  I was saying that X `is likely the b i g g e r issue`, and the filter removed the word "__\&\+\+\%\%\$__", calling it profane.  I have since changed it to "more important".

It has done it here as well 🤦‍♂️.

**Comment by mdell-seradex** [comment]
It seems that it has no clue about context.

**Comment by IEvangelist** [comment]
You're not wrong, it is really primitive... I addressed this issue here ed60b6160aae4fbb5bbf68ce197a125eeb1bbddd.
